# Ensures that sudo is disabled, so that containerized builds are allowed
sudo: false

os:
 - linux
 - osx
language: c
compiler:
 - clang
 - gcc
addons:
  apt:
    # we need a more recent cmake than travis/linux provides (at least 2.8.9):
    sources:
    - kubuntu-backports
    packages:
    - cmake
    - python3
    - valgrind
before_install:
 - |
     if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ]
     then
         echo "Building without python3, to make sure that works."
     fi
 - |
     if ( test "`uname -s`" = "Darwin" )
     then
       #cmake v2.8.12 is installed on the Mac workers now
       #brew update
       #brew install cmake
       echo
     else
       #install a newer cmake since at this time Travis only has version 2.8.7
       echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
       sudo apt-get update -qq
       sudo apt-get install cmake
     fi

script:
 - make
 - make test
 - |
     if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]
     then
         make leakcheck
     fi
