environment:
  PYTHON: "C:\\Python34"
  PYTHON_VERSION: "3.4.1"
  PYTHON_ARCH: "32"

build_script:
  - |
    mkdir build 2> nul
    pushd build
    cmake -G "NMake Makefiles" -D CMAKE_BUILD_TYPE="Release" -D CMAKE_INSTALL_PREFIX="windows"
    nmake /nologo
    popd

test_script:
  - |
    pushd build && nmake /nologo test

